version: '3'
networks:
  db-bridge-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.24.0.0/24
volumes:
  mysql-db-volume:
services:
  mysql-db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=mydb
    volumes:
      - mysql-db-volume:/var/lib/mysql
    networks:
      - db-bridge-network
    ports:
      - 33060:3306